### ISSUE TITLE
Need to build lab

### ISSUE THREAD

**Issue by dfenjves** [learn-co-curriculum/sinatra-dynamic-routes-lab#1]
Reference [Readme](https://github.com/learn-co-curriculum/sinatra-dynamic-routes-lab) for outline of content.

deadline: 9/15

**Comment by AnnJohn** [comment]
@dfenjves updated your issue description with a link to the Readme with the outline and a deadline. Could you have all issues just read like that going forward? Thanks

**Comment by dfenjves** [comment]
Done
