### ISSUE TITLE
Code passed-but wrong

### ISSUE THREAD

**Issue by CodeByLine** [learn-co-curriculum/sinatra-dynamic-routes-lab#10]
My code for the 5th task (`Create a dynamic route at get '/:operation/:number1/:number2' that accepts an operation (add, subtract, multiply or divide) and performs the operation on the two numbers provided. For example, going to /add/1/2 should render 3`) of the lab passed, but I could not get the page to render (using "shotgun")--looked at solutions and saw that my code was wrong. Below is my code that passed:

```
    if @operation == "add"
      "#{number1} + #{number2}"
    elsif @operation == "subtract"
      # @operation = -
      "#{number1} - #{number2}"
    elsif @operation == "multiply"
      # @operation = *
      "#{number1} * #{number2}"
    else
      # @operation = /
      "#{number1} / #{number2}"
    end
```

**Comment by gj** [comment]
Thanks for pointing this out @CodeByLine !
