### ISSUE TITLE
Clarify what a sentence is for the sake of the lab?

### ISSUE THREAD

**Issue by churchwerks** [learn-co-curriculum/sinatra-dynamic-routes-lab#19]
So I have a problem with one of the instructions and therefore also one of the tests in this lab.
Instruction number 4 says 
> Create a dynamic route at get '/say/:word1/:word2/:word3/:word4/:word5' that accepts five words and returns a string with them formatted as a sentence.

A sentence to me, begins with a capital letter and ends with a punctuation character.

So I had my code format the string with :word1 capitalized and a period at the end of :word5 with a space in between all words.

Here is my code snippet and beneath that is the failing test.
  get '/say/:word1/:word2/:word3/:word4/:word5' do
    words = []
    words[0] = params[:word1]
    words[1] = params[:word2]
    words[2] = params[:word3]
    words[3] = params[:word4]
    words[4] = params[:word5]
    phrase_string = ""
    counter = 0
    until counter == words.size
      phrase_string << "#{words[counter]} "
      counter += 1
    end
    phrase_string.chop! << "."
    "#{phrase_string.capitalize!}"
  end

Failures:

  1) App GET /say/:word1/:word2/:word3/:word4/:word5 concatenates the words and adds a period
     Failure/Error: expect(last_response.body).to include('stop rhyming I mean it.')
       expected "Stop rhyming i mean it." to include "stop rhyming I mean it."
     # ./spec/sinatra_dynamic_routes_lab_spec.rb:75:in `block (3 levels) in <top (required)>'

So I quickly figured out that I shouldn't use capitalize! because not only did it capitalize the First word , it downcased the I to i. Rather than performing some Regex magic to correct this, I just changed the return value to: "#{phrase_string}" which passed the test spec.

No big deal. I spent a few extra minutes figuring this all out, but for some students this could have been a major time suck. So I would suggest, rewording the instructions to say exactly how the string should be formatted, instead of "them formatted as a sentence.", which is pretty vague and actually not correct in this case.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We clarified the instructions.

As always thank you for contributing!
