### ISSUE TITLE
Typo in spec_helper line 3?

### ISSUE THREAD

**Issue by joanrig** [learn-co-curriculum/sinatra-dynamic-routes-lab#20]
line 3 was 
'require_relative '../config/environment'

i changed it to: 
'require_relative '../config/environment.rb'

to get tests to run

**Comment by drakeltheryuujin** [comment]
Hi there,
I'm having difficulty reproducing the issue, so I'm going to close it for now. The spec_helper file seems to work as is.  If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!
As always, thanks for contributing! 💙
