### ISSUE TITLE
Not very intuitive!

### ISSUE THREAD

**Issue by Xabier-Casan-Abia** [learn-co-curriculum/sinatra-dynamic-routes-lab#21]
The specs of last step make you have to pass the results of each operation as a string without any clue in the instructions.

**Comment by Sdcrouse** [comment]
Hi. I'm not sure if they changed the README since you raised this issue, but the instructions for one of the previous steps mention that the return value of a route needs to be a string.

Hope that helps!

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
