### ISSUE TITLE
Regarding the /:operation/:number1/:number2 criteria 

### ISSUE THREAD

**Issue by mcummings128** [learn-co-curriculum/sinatra-dynamic-routes-lab#22]
This test states: "_Create a dynamic route at get '/:operation/:number1/:number2' that accepts an operation (add, subtract, multiply or divide) and performs the operation on the two numbers provided. For example, going to /add/1/2 should render 3._"

One would assume you want an integer returned. Yet, the answer is a string. Specify that you want the answer returned as a string, because my methods were working just fine returning integers and it's somewhat ridiculous that even the **instructions** make it appear as though an integer should be returned.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
