### ISSUE TITLE
Regarding the /say/:number/:phrase instructions

### ISSUE THREAD

**Issue by mcummings128** [learn-co-curriculum/sinatra-dynamic-routes-lab#23]
The instructions state "_Create a dynamic route at get '/say/:number/:phrase' that accepts a number and a phrase and returns that phrase in a string the number of times given._"

This can be read one of two ways:
1. Return the same phrase n times, making a very long string with that phrase in it that amount of times.
2. Return the phrase as a string n number of times.

This can be confusing because one person may think (if phrase was "hello" and number was 4) that the string should be "hellohellohellohello" and another person may think you would want to return "hello" 4 times. Please consider rewording--the test criteria is somewhat helpful but still cryptic for newer students.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
