### ISSUE TITLE
Hints for Context

### ISSUE THREAD

**Issue by kjgenevieve** [learn-co-curriculum/sinatra-dynamic-routes-lab#24]
Hello,

It would be nice if this lab mentioned that we need to create a view erb document and to use <%= %> to use Ruby methods.

cc: @carnold18

**Comment by drakeltheryuujin** [comment]
Hi there,

There's no views required to pass the tests in this lab, so I'm going to close this issue as it seems to be opened in the wrong place. If I've made a mistake, please reopen the issue and provide more detail about how this lab can be improved. Thanks for your feeback!
