### ISSUE TITLE
Tests pass with incorrect code

### ISSUE THREAD

**Issue by kaylee42** [learn-co-curriculum/sinatra-dynamic-routes-lab#6]
FYI, tests for the last route pass without functioning code. My tests started passing with something like this: 

get '/:operation/:number1/:number2' do 
num1 = params[:number1].to_i
num2 = params[:number2].to_i
case params[:operation]
when add
  "#{num1 + num2}"
end
end

ALL of the tests for this route were passing even though I didn't have anything written for multiply/subtract/divide.

**Comment by AnnJohn** [comment]
Thanks for raising the issue! We'll look into it.

**Comment by victhevenot** [comment]
hey @kaylee42 this is an awesome solution to this lab!! You figured out a way to make the operation dynamic as well. It's absolutely fine that this passed all the tests. You figured out a great way to write way less code and still achieve the same result.
