### ISSUE TITLE
rspec line 59: " 'GET //:operation' " 

### ISSUE THREAD

**Issue by authorbeard** [learn-co-curriculum/sinatra-dynamic-routes-lab#8]
line 59 says "describe 'GET //:operation  ...". I kept failing tests because I wrote my action with the double slashes there. Which is a little embarrassing to admit, but I usually assume first that it's just something I haven't learned yet.

**Comment by AnnJohn** [comment]
thanks @authorbeard for pointing out the typo. We will update this soon.
